# Generated by Django 4.2.3 on 2023-11-29 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0002_alter_order_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='images',
            new_name='image',
        ),
    ]
